version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /Users/spencerpro/Documents/GitHub/quizlaw/backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quizlaw
    command: python -m app.main

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"  # Using port 3000 as requested
    volumes:
      - /Users/spencerpro/Documents/GitHub/quizlaw/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quizlaw
    ports:
      - "5432:5432"

volumes:
  postgres_data: